### ISSUE TITLE
[SOLVED] Titanium Backup, Cannot Integrate to ROM

### ISSUE THREAD

**Issue by arrmo** [coretechsystems/AptOS-G900A#10]
Hi,

When trying to integrate to ROM, this often fails, and then the app is gone / trashed. Is this perhaps the same issue you're trying to resolve about being able to install OpenGApps?

And is there an easy way to install an update (.apk) to the System partition?

Thanks!

**Comment by coretechsystems** [comment]
Check if there are any libraries in the .apk that need to go into the system "lib" folder, and move them if necessary by extracting them from the APK with a utility like 7-zip.
To install an APK to the system, first follow the above instructions, and then put the apk in the /system/app or /system/priv-app folders (depending on the nature of the app), chmod the directory rwxr-xr-x and the apk rw-r-r

**Comment by arrmo** [comment]
OK, by no means an expert on apk's, so perhaps a dumb question, but ...
1) To the system "lib" folder - only any lib folders inside the apk, right?
2) For app vs priv-app ... is this meaning apps that require root access?

Thanks!

**Comment by coretechsystems** [comment]
1. Yes, only put the contents of the lib folder of the APK into the system lib folder.
2. priv-app is for applications that require system-level privileges. All other applications go to the regular "app" folder. A good example of this is the Calculator, it didn't need system-level privileges, so it went into the "app" folder.

**Comment by arrmo** [comment]
Works perfectly - thanks!

Not sure why Titanium Backup fails then - odd.

**Comment by coretechsystems** [comment]
Happy To Help!
Question marked resolved.
