### ISSUE TITLE
Resize System Partition

### ISSUE THREAD

**Issue by arrmo** [coretechsystems/AptOS-G900A#12]
My system partition looks to be ~ 2.5 GB ... pretty large (and a bit wasteful), no?

Thanks!

**Comment by coretechsystems** [comment]
Yeah I can see what you mean.. due to the nature of this I'll work on it after the more major stuff is worked out.
I'm pretty sure we would be able to just make the installer execute a shell script that runs busybox/fdisk or gparted and fixes the partition before rebooting into the OS.

**Comment by arrmo** [comment]
Yep, definitely low priority - agreed!

**Comment by AptLogic** [comment]
After looking further into the concept of repartitioning the device (especially a bootloader-locked device like klteatt), I have decided that the trouble it would take to free about 1GB of space (2.4.5 is expected to use 1.5gb) isn't worth the elevated chances of bricks.
Maybe when I have more time to explicitly into this matter (and when my test device isn't also my daily driver), this will change.

**Comment by arrmo** [comment]
No worries - understood, and agreed. Thanks!
