### ISSUE TITLE
Settings Crash when adding widget

### ISSUE THREAD

**Issue by Noodlez1232** [coretechsystems/AptOS-G900A#21]
Bug Name: Settings Crash when adding widget
Bug ID: 21
Area Path: com.android.settings and is.shortcut
Build Number: *
Severity: 3
Priority: 2
Assigned to: @AptLogic
Reported By: NateDogg1232
Reported On: 12/20/2017

Description:
Adding a widget to a third-party launcher causes a crash in settings.
Launcher: Evie launcher

Steps To Reproduce:
Use Evie Launcher
Attempt to add a widget

Expected result: Normal Widget placement

Notes:
To be fair, this is not happening on the default launcher, nor on the launcher Lawnchair, but this issue with Settings crashing when attempting such does only happen on this ROM, as I have this launcher on different devices and have been using the launcher for almost a year now on a different device.

I don't know if this happens with all settings crashes, but with this crash, there is no "report" button, which would normally allow me to get a log to put in issue submissions.

**Comment by AptLogic** [comment]
Bug ID, severity, and priority assigned.
If you would be able to capture a logcat for the process after the crash occurs, that would be great.
One way I capture logcats for these crashes is by getting the aLogcat (root) app, and then filter the output to only show AndroidRuntime logs, and then when the crash occurs the Process ID will be in the log, and then all you have to do is change the filter to the Process ID to get the full log.
