### ISSUE TITLE
Live Wallpaper - Unable to Set

### ISSUE THREAD

**Issue by arrmo** [coretechsystems/AptOS-G900A#8]
Bug Name: Live Wallpaper - Unable to Set
Bug ID: 8
Area Path: Wallpapers
Build Number: AAT2N-16w4d
Severity: 1
Priority: 2
Assigned to: AptLogic/coretechsystems
Reported By: arrmo
Reported On: 04/23/2017

Description:
Trying to set Live Wallpaper, error message saying App isn't installed (but it is!).

Steps To Reproduce:
Wallpapers, Live Wallpaper, then select one.

Expected result: Able to select wallpaper (and set it).

Logs:

Screenshots:

**Comment by coretechsystems** [comment]
Bug ID, Severity, and priority assigned.
Bug was replicated but in a different fashion that uses the same principle. Bug is most likely due to the absence of the LiveWallpaperChooser package, which was removed in the X ROM and never added back to AptOS.
A fix will be researched and a test of the bugfix will be committed to the explorer repository by tomorrow (Monday 04/24)

**Comment by coretechsystems** [comment]
A bugfix has entered testing in the EXPLORER builds.
Basically I put the LiveWallpaperChooser back in and we'll see what happens.

**Comment by arrmo** [comment]
Thanks! Trying to figure out how to select EXPLORER in OTA, then I'll update and test it out.

**Comment by coretechsystems** [comment]
To prevent people that don't understand the risks of using the Explorer builds from getting their hands on it, you can't just select the Explorer channel from the OTA app, you have to change a build.prop value.
In this case, change ro.ota.manifest to http://aptget.azurewebsites.net/aptosklteatt/explorer/fota.xml
After that, wipe the OTA updater's data and launch it.

The OTA system for Explorer builds uses a new, experimental updater that tries to update the system completely without wiping user data. If anything doesn't work at any stage in the installation process, file a bug report and I'll get you the normal installer. Thanks for being a part of the Explorer program!

**Comment by coretechsystems** [comment]
The fix has successfully passed testing in Explorer build AAT1R, and will be present in release version 2.4.5.

**Comment by arrmo** [comment]
Thanks!

**Comment by arrmo** [comment]
Hmmm ... tried this => mount system r/w, edit build.prop, system back to ro. Then kill OTA app (just in case), clear data ... restart. Not finding the update - or is it not there now?

Thanks!

**Comment by coretechsystems** [comment]
What's the value of ro.ota.verison? It has to be set to something lower than 4. Also check that the ro.ota.manifest value is correctly set to https://aptget.azurewebsites.net/aptosklteatt/explorer/fota.xml

**Comment by arrmo** [comment]
Yep, it is ... just checked,
ro.ota.version=1

And I manually changed the manifest value, also copied here,
ro.ota.manifest=https://aptget.azurewebsites.net/aptosklteatt/explorer/fota.xml

All look correct?

**Comment by coretechsystems** [comment]
Looks right to me... don't know why it wouldn't be working then. Just download the zip from http://qc4.androidfilehost.com/dl/LWiH1NS_c2Qd_4tDHedoPw/1493227133/745425885120726670/BEGONIAXP-klteatt-17w1d1b-SYSDLUP.zip and flash without any wipe commands.

**Comment by arrmo** [comment]
No worries - we can try to debug it if you want (different ticket?). 

Thanks!

**Comment by coretechsystems** [comment]
I'll take it through some more testing and then if I still can't figure out what's wrong we can open a ticket. It might just be a trivial problem I can fix in five minutes.

**Comment by arrmo** [comment]
WFM, NP - thanks!

**Comment by coretechsystems** [comment]
Glad to know you got it :)

**Comment by arrmo** [comment]
Yep - and after an install, now it checks Explorer releases! BTW, is there a change log anywhere for them? It's already downloading a new one ... ;-).

BTW, yep the fix works for Live Wallpapers. Thanks!

**Comment by coretechsystems** [comment]
The new update is just the same update. That's because the value that controls the ota version in the build.prop is set to 3 but the version in the AptOS OTA database is set to 4. You can safely ignore that release for now.

**Comment by arrmo** [comment]
I will, but so you know ... downloaded, and the MD5 checksum failed.
